### ISSUE TITLE
registration procedure error

### ISSUE THREAD

**Issue by critot** [dlmelendez/identityazuretable#1]
Hi,
thank you for your wonderful work,  that I'm testing to use it in my azure app.
I think there is a bug in the registration procedure, in particular:
when I register a new user with an email that already exist, I get this error

Object reference not set to an instance of an object
GetUserIdAsync

stack:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ElCamino.AspNetCore.Identity.AzureTable.UserStore`7.GetUserIdAsync(TUser user, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.<GetUserIdAsync>d__78.MoveNext()
...
...samplemvccore\Controllers\AccountController.cs:line 109
(call from:  var result = await _userManager.CreateAsync(user, model.Password);)

with default Identity Provider normally I go back to the registration form with the reporting of the error in the field --> User name 'email' is already taken.

thank you

**Comment by turowicz** [comment]
I have the same error here - only with no users in table

**Comment by hossamdarwish** [comment]
I have the same error here with no users in table, the User Id is not generated and returns Null when calling GetUserIdAsync.

My workaround is generate the User Id explicitly in your ApplicationUser Model like this

`public class ApplicationUser : IdentityUser
    {
        public ApplicationUser()
        {
            GenerateKeys();
        }
    }`
HTH till we have a fix

**Comment by dlmelendez** [comment]
Looking in to this. Been afk for a while.
Thanks,
Dave

**Comment by dlmelendez** [comment]
Make sure you as using the Azure storage library WindowsAzure.Storage 7.1.3-preview. 
7.2 has a bug that I reported here: [https://github.com/Azure/azure-storage-net/issues/341](url) . Please give this a shot and let me know if you are still seeing a problem.

**Comment by critot** [comment]
yes, I'm using WindowsAzure.Storage 7.1.3-preview; the bug I described is simple to reproduce, could you take a look?
thank you

**Comment by dlmelendez** [comment]
I have a fix that I am testing now. However, I am investigating a possible bug in the identity core framework that is not adding the duplicate username and email error descriptions correctly.

**Comment by dlmelendez** [comment]
Fixed with release 1.6 the above workaround should no longer be used. Thanks for reporting the issue!

**Comment by critot** [comment]
it works! thank you
