### ISSUE TITLE
Blazor / NET 8

### ISSUE THREAD

**Issue by github5775** [dlmelendez/identityazuretable#105]
Dave

Do you see any issues with using the **_Identity_** part of this project with Blazor and NET 8, as is, other than adjusting how it's added in DI?  (I may or may not need the actual Account pages.)

Michael

**Comment by dlmelendez** [comment]
I will take a look closer to the .net 8 release this month.

**Comment by dlmelendez** [comment]
Looks like there is no breaking changes in .net8 rc2. I will merge rel/8.0 to master and release when .net8 goes GA..

**Comment by github5775** [comment]
That makes sense...thank you.  I am looking to substitute your Table lib into this Server project to test it with hosted WASM:

https://github.com/carlfranklin/AddIdentityWasm/blob/master/AddIdentityWasm/Server/Program.cs

`builder.Services.AddDefaultIdentity<ApplicationUser>(options=> options.SignIn.RequireConfirmedAccount = true)
    .AddRoles<IdentityRole>()
    .AddEntityFrameworkStores<ApplicationDbContext>();`
