### ISSUE TITLE
Claims: ArgumentException: Object of type 'System.DateTimeOffset' cannot be converted to type 'System.DateTime'.

### ISSUE THREAD

**Issue by tbasallo** [dlmelendez/identityazuretable#109]
I get the following exception when trying to get users that have a claim. This used to work.

Getting claims for a single user works fine.

```
ArgumentException: Object of type 'System.DateTimeOffset' cannot be converted to type 'System.DateTime'.
Users = await _userManager.GetUsersForClaimAsync(new System.Security.Claims.Claim(Auth.Role, Role));
```

.net7 and .net 8
Versions 7-8

Do I need run a migration?

**Comment by tbasallo** [comment]
This error also comes up when trying to delete a user:
      
await _userManager.DeleteAsync(AppUser);

**Comment by dlmelendez** [comment]
Please follow the data migration https://elcamino.cloud/projects/docs/identityazuretable/migration.html.

**Comment by dlmelendez** [comment]
Closed for inactivity.
