### ISSUE TITLE
Generate Recovery Codes does not update

### ISSUE THREAD

**Issue by KevinLedge** [dlmelendez/identityazuretable#113]
There is a bug when you have Two Factor Auth enabled and press the 'reset recovery codes' button.

GenerateRecoveryCodes.cshtml.cs
var recoveryCodes = await _userManager.GenerateNewTwoFactorRecoveryCodesAsync(user, 10);

This line updates the timestamp in AspNetUsers on the RecoveryCodes TokenName row but does not update the TokenValue.

If I manually delete the row before calling that line then everything works.

I am running version 8 of ElCamino and Microsoft.AspNetCore.Identity.UI 8.0.3.

I created a new user to test this.

**Comment by dlmelendez** [comment]
Fixing this bug in 9.0 release.

**Comment by dlmelendez** [comment]
Fixed in v9.0
