### ISSUE TITLE
Trying to use an example but it doesn't work

### ISSUE THREAD

**Issue by t1fra** [dlmelendez/identityazuretable#114]
Hi,
thanks for creating this solution. I would love to try it out but im having issue(s).

I've create a asp.net core 8 mvc sample project with authentication for individual accounts
- When running the standard Microsoft project sample I do see a register/login button.

Afterwards I followed your quickstart instructions to get a sample, had to add --force to overwrite existing files.

```
dotnet new --install ElCamino.AspNetCore.Identity.AzureTable.Templates
dotnet new mvc-id-azure-tables --force 
```
When running the WebApp now, the buttons to register/login are gone. I've placed a breakpoint in _LoginPartial.cshtml to see if this view is rendered. The break point is not reached.

I also created a asp.net core 8 mvc project without any authentication, -- force not required as no files exist for identity. Same result, break point in _LoginPartial.cshtml is not reached and no register/login buttons are visible.

Could you please advise what I'm missing?

**Comment by t1fra** [comment]
No idea what went wrong, trying it again on a new project was working :-)

**Comment by dlmelendez** [comment]
Closed for inactivity.
