### ISSUE TITLE
Support injecting TableServiceClient

### ISSUE THREAD

**Issue by martincostello** [dlmelendez/identityazuretable#115]
When using `TableServiceClient` with [.NET Aspire](https://learn.microsoft.com/dotnet/aspire/storage/azure-storage-tables-component?tabs=dotnet-cli), the recommended approach is to configure just the URI for the table and use RBAC to configure permissions to access the table.

However if the "connection string" is just a URI, the below fails as that is not a valid connection string:

https://github.com/dlmelendez/identityazuretable/blob/f5cc8e321e63923771ae2149a0e20d774d921bb2/src/ElCamino.AspNetCore.Identity.AzureTable/IdentityCloudContext.cs#L33

.NET Aspire [supports both connection strings and a service URI](https://github.com/dotnet/aspire/blob/2249f7d4d114784ed4f117a60b1b2963d971bd92/src/Components/Aspire.Azure.Data.Tables/AspireTablesExtensions.cs#L80-L82) to create instances of `TableServiceClient`.

For now I've stuck with using a storage connection string to both `IdentityCloudContext` and .NET Aspire work together with the same configuration setting. The ideal solution would be for `IdentityCloudContext` to allow a way to inject a `TableServiceClient` (e.g. a factory delegate property on `IdentityConfiguration`) so that the client registered with DI by .NET Aspire can be used instead of this library creating one itself.

**Comment by dlmelendez** [comment]
I will be adding a parameter for the TableServiceClient to be added into di from IdentityBuilder.AddAzureTableStores. This should solve this issue.

**Comment by dlmelendez** [comment]
Fixed in v9.0
