### ISSUE TITLE
WindowsAzure.Storage dependency issue

### ISSUE THREAD

**Issue by tiksn** [dlmelendez/identityazuretable#12]
I can't update ElCamino.AspNetCore.Identity.AzureTable from version 1.6.1 to 1.6.2 because your NuGet strictly depends on WindowsAzure.Storage 7.1.3-preview. I have WindowsAzure.Storage 8.0.0 for all my solution projects. Please fix this issue.

`error: Version conflict detected for WindowsAzure.Storage. 
error:  MobileWebService (>= 1.5.0) -> DataModel  -> WindowsAzure.Storage (>= 8.0.0) 
error:  MobileWebService (>= 1.5.0) -> ElCamino.AspNetCore.Identity.AzureTable (>= 1.6.2) -> 
WindowsAzure.Storage (= 7.1.3-preview).
log  : Writing lock file to disk. Path: E:\VSTS\tiksn\Grocery Checklist\Code\MobileWebService\project.lock.json
log  : E:\VSTS\tiksn\Grocery Checklist\Code\MobileWebService\MobileWebService.xproj
log  : Restore failed in 54689ms.
Errors in E:\VSTS\tiksn\Grocery Checklist\Code\MobileWebService\MobileWebService.xproj
    Version conflict detected for WindowsAzure.Storage.
     MobileWebService (>= 1.5.0) -> DataModel  -> WindowsAzure.Storage (>= 8.0.0)
     MobileWebService (>= 1.5.0) -> ElCamino.AspNetCore.Identity.AzureTable (>= 1.6.2) -> WindowsAzure.Storage (= 7.1.3-preview).
`

**Comment by dlmelendez** [comment]
@tiksn this was put in place for issue #7 where there was a bug in the Windows.Storage package in 7.2 and 7.2.1 causing a priority 0 failure. Working to release 1.6.5 in the next day or so with an update to include Windows.Storage 8.0 which fixes the problem. I just tested the updated storage library and it looks good to go. Stand by for release.
Thanks for reporting the issue.

**Comment by dlmelendez** [comment]
https://github.com/dlmelendez/identityazuretable/releases/tag/v1.6.5
