### ISSUE TITLE
identityazuretable with IdentityServer4?

### ISSUE THREAD

**Issue by CodeEXc** [dlmelendez/identityazuretable#14]
Hi @dlmelendez,
does identityazuretable works with a IdentityServer4?

Thank you

**Comment by dlmelendez** [comment]
Yes! Follow the directions on the IdentityServer4 site https://identityserver4.readthedocs.io/en/release/quickstarts/6_aspnet_identity.html with the instructions https://dlmelendez.github.io/identityazuretable/#/walkthroughcore to modify the IdentityCore settings. I have tested the basic authentication workflows and seems to work well.
Thanks,
Dave
