### ISSUE TITLE
How To Manually Add Role to User

### ISSUE THREAD

**Issue by bradjolicoeur** [dlmelendez/identityazuretable#15]
I have only two users that need and admin role for my app and I was hoping to avoid creating a user management UI.  Is there a way to manually add the roles to a user using Azure Storage Explorer?

I assume I need to make an entry in the AspNetRoles table, but I'm not sure what to put in each column.

**Comment by dlmelendez** [comment]
@bradjolicoeur unfortunately, using the Azure storage explorer would be a lot of work to get the users and roles added properly. I would recommend modifying the unit test to create the roles and then assign them to your users. Take a look at [CreateRole ](https://github.com/dlmelendez/identityazuretable/blob/master/tests/ElCamino.AspNet.Identity.AzureTable.Tests/RoleStoreTests.cs) test for creating the roles, mainly the RoleManager.CreateAsync(role); and this user test to add the role to the user helper [AddUserRoleHelper](https://github.com/dlmelendez/identityazuretable/blob/master/tests/ElCamino.AspNet.Identity.AzureTable.Tests/UserStoreTests.cs) looking mainly at the UserManager.AddToRoleAsync() method. Should be able to get going in a few lines of code.

**Comment by bradjolicoeur** [comment]
@dlmelendez  Thank you for the advice.  I was able to use the unit tests to add the roles I needed as you suggested.
