### ISSUE TITLE
Docs Sample?

### ISSUE THREAD

**Issue by ardalis** [dlmelendez/identityazuretable#19]
I'm working on docs for writing custom identity providers for aspnet core. Would you be interested in assisting me with using your azure provider as a sample in the documentation?

**Comment by dlmelendez** [comment]
@ardalis Sure. The project is under the MIT license so just follow those guidelines where appropriate when referencing. It would great to get a link to your documentation **_if_** you are making in publicly available to share on this project site. Good luck on the docs.

**Comment by ardalis** [comment]
Sounds good. To be clear I'm referring to the docs.asp.net docs. Thanks.

Steve Smith

**Comment by dlmelendez** [comment]
Cool. Look forward to checking it out.
