### ISSUE TITLE
Sample app references v. 1.6 which doesn't exist in NuGet

### ISSUE THREAD

**Issue by DeveloperUniversity** [dlmelendez/identityazuretable#2]
When attempting to load the MVC5 sample, (\identityazuretable-master\sample\), to work with the "samplemvc" project, and then Restore NuGet Packages for Solution, you'll get an exception:

NuGet Package restore failed for project samplemvc: Unable to find version '1.6.0' of package 'ElCamino.AspNet.Identity.AzureTable'.
  https://www.myget.org/f/aspnetmaster/api/v3/index.json: Package 'ElCamino.AspNet.Identity.AzureTable.1.6.0' is not found on source 'https://www.myget.org/f/aspnetmaster/api/v3/index.json'.
  https://api.nuget.org/v3/index.json: Package 'ElCamino.AspNet.Identity.AzureTable.1.6.0' is not found on source 'https://api.nuget.org/v3/index.json'.
.

There doesn't seem to be a 1.6 published to NuGet, only 1.5.4.

**Comment by dlmelendez** [comment]
Yes, that is a bug. 1.6 has been delayed a bit. This should be fixed once I get 1.6 out the door.
Thanks,
Dave

**Comment by DeveloperUniversity** [comment]
Thank you, and fwiw, I was able to simply follow your well written instructions here:

https://dlmelendez.github.io/identityazuretable/#/walkthrough

... and it only took a few minutes to get up and running.

**Comment by dlmelendez** [comment]
Fixed with 1.6 release.
