### ISSUE TITLE
Incorrect time shift for LockoutEndDateUtc 

### ISSUE THREAD

**Issue by Niklas-Peter** [dlmelendez/identityazuretable#21]
My local time (Germany) is UTC+2.

I set 
`options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromHours(4); `

and forced the lockout at 7.30 (UTC). However, in the database 9.30 is saved instead of the expected result 11.30. I think it is caused by your time conversions. Using the EntityFramework ASP.NET Identity storage it works as expected.

**Comment by dlmelendez** [comment]
@Niklas-Peter Thanks for reporting this. Yes, it looks like this logic was moved from the EF store into the UserManager at some point. Which package (aspnet or aspnetcore) are you using and what version?
Thanks,
Dave

**Comment by Niklas-Peter** [comment]
The current version for ASP.NET core: ElCamino.AspNetCore.Identity.AzureTable 1.6.6

**Comment by dlmelendez** [comment]
@Niklas-Peter  Fixed in release 1.6.7. Thanks, Dave
