### ISSUE TITLE
Error on removing from Role

### ISSUE THREAD

**Issue by incandera** [dlmelendez/identityazuretable#22]
David, thanks for your work on this great library; have been able to successfully implement and use the basic cases fully.

However, I am running into some unexpected behavior when removing a User from a Role with a full-on many-to-many scenario, i.e. with many Users in many Roles. This is using the **ASP.NET MVC5** version.

**Example**:

- Role **A**, Role **B**, Role **C**
- User 1
- User 1 is in all Roles

Using the method RoleManager.**RemoveFromRole**(userId, roleId), I am observing the following:

Removing User 1 from Role **B**: results in removal of User 1 from Role **A**. _User 1 remains in Role **B** and **C**_.
Removing User 1 from Role **C**: results in removal of User 1 from Role **B**. _User 1 remains in Role **C**_.
Removing User 1 from Role **C**: results in removal of User 1 from Role **C**. _User 1 is no longer in any Role_.

In sum: removal actually does work, just that the removal doesn't seem to "target" correctly. Not sure if I'm describing it correctly -- seems almost as if the removal targets the Role which _precedes_ the targeted Role in whatever default sort order the Roles are in, in the list of Roles the User belongs to.

I have verified (debug) that the given User is indeed in whatever Role I am testing; that the list of Role memberships for the User is correct and complete; that the IDs of the User and Role in any given remove operation are correct; and, finally, that RoleManager.**RemoveFromRole**(userId, roleId) does return IdentityResult.Success = true.

And yet: _the User is removed from the wrong Role_. 

I am seeing the User-to-Role relationships stored in the AspNetUsers Azure Table according to the specifications described in your technical documentation.

Is there something you can recommend that I try? Or perhaps I am misusing the RoleManager, UserManager functionality?

Thank you!

**Comment by dlmelendez** [comment]
I will take a look and see if I can repro this issue.

**Comment by dlmelendez** [comment]
@incandera I think you are referring UserManager.RemoveFromRoleAsync() . This signature is public virtual Task<IdentityResult> RemoveFromRoleAsync(TKey userId, string role); in the UserManager. However, it takes the role:name as the string:role parameter not the role:id. That might be the problem you are running into. Take a look at the test method AddRemoveUserRole() at line 1048 https://github.com/dlmelendez/identityazuretable/blob/master/tests/ElCamino.AspNet.Identity.AzureTable.Tests/UserStoreTests.cs and this should give you a good example to work from. Thanks, Dave

**Comment by incandera** [comment]
Hi Dave, thanks for looking further into this. Unfortunately, that doesn't seem to be it. Given a role with:

**Id**: "R_ACCOUNT_20MANAGER"
**Name**: "Account Manager"

Passing in the **Id** results in the behavior described in the original issue description. But passing in the **Name** results in the RemoveFromRole() method returning false with "User is not in role"... Regards, Allen

**Comment by dlmelendez** [comment]
No longer testing on AspNet MVC5. No repro on current code base.
