### ISSUE TITLE
ASP.NET Core Identity 2.0 support

### ISSUE THREAD

**Issue by xperiandri** [dlmelendez/identityazuretable#23]

**Comment by DreamingDevs** [comment]
@dlmelendez Please let us know when can we expect support for ASP.NET Core 2.0?

**Comment by xperiandri** [comment]
@dlmelendez, I created pull request.
You can pack a package from my sources meanwhile.
Anyway we want to know when

**Comment by dlmelendez** [comment]
@xperiandri appreciate the pull request. It is a big request and it will take time to review and test it all. I have a pending change for the last release 1.7 to support classic identity and core 1.x to go out first and then this feature is top priority. I, like all of you, have a day job too, so I will do my best to get this release in the next week or so.

**Comment by xperiandri** [comment]
Thanks
If you still want to keep Core 1.x and full framework builds, you would better take my refactored tests first.
As basically I don't remember that I changed anything in your logic but only removed cross compile directives.

**Comment by dlmelendez** [comment]
There is some weird windowsazure.storage library exceptions happening on loading a net461 test project with the netstandard2.0 elcamino library. The storage library team is working on [netstandard2.0 support ](https://github.com/Azure/azure-storage-net/issues/491)but it is not ready yet and I think it will solve the problems. Basically, the storage library is only working on the netstandard2.0 in a backwards compat state that really isn't fully baked yet. I will do a release as 2.0-beta0 with (net461 and netstandard2.0 targets, only including net461 as a workaround for the storage library exception for now) but I am not going to move out of beta until the windowsazure.storage library fully supports netstandard2.0.
Changes are going into rel/2.0 branch where I merged in @xperiandri 's initial work and checked in a ton of refactoring for identity core 2.0.

**Comment by dlmelendez** [comment]
v2.0 released.
