### ISSUE TITLE
Invalid Table Prefix Fails Silently

### ISSUE THREAD

**Issue by tbasallo** [dlmelendez/identityazuretable#28]
After going through code again and again and comparing my code to the samples, I realized that the underscore ("_") in my prefix might be causing for my setup not to work.

Sure enough, changing from ID_ to ID fixed the issue. The tables were created as expected.

I think that an exception should be thrown to keep people sane :)

**Comment by tbasallo** [comment]
Just came across this https://github.com/dlmelendez/identityazuretable/issues/9 

Not sure if an internal check for known invalid name would help. Feel free to close if you still feel the wontfix applies. I'm not closing just in case you want to reconsider.

**Comment by dlmelendez** [comment]
@tbasallo I feel your frustration on this one. I think the answer might be to add logging to project to surface the errors raised. This might be good solution to cover more than just this particular scenario.
