### ISSUE TITLE
Feature Request: Supporting Multi-tenancy w/ change to Partition Key

### ISSUE THREAD

**Issue by DeveloperUniversity** [dlmelendez/identityazuretable#3]
Hi, right now, for a given user, both the Partition Key and Row Key are set to the HTML encoded version of the user's email address.

However, to support multi-tenancy, I think all you would need to do is change Partition Key to the ID of the tenant website.  Admittedly, most applications are not multi-tenant, so this would always be the name of the only tenant, the website's name or some default.

However, what if you want single code base to support the same user on multiple tenant sites, like an SaaS, then you could have:

PK: TENANT-WEBSITE01  RK: U_BOB_40DEVU.COM
PK: TENANT-WEBSITE02  RK: U_BOB_40DEVU.COM
PK: TENANT-WEBSITE03  RK: U_BOB_40DEVU.COM

Three separate login accounts across three separate sites, but one user / email address.

Then permissions could be different on a per tenant website basis, etc.

Yes, you do have support for multi-tenancy at the TABLE level (one set of tables PER TENANT) via the tablePrefix configuration property, however what I'm suggesting is multi-tenancy at the ROW level (one set of tables for ALL tenants).  

The problem (for me) with each tenant getting its own set of tables is that it would make management more difficult.  First, it would explode the number of tables in a given account.  Second, I would have to deploy a single code base to multiple Azure Web accounts, one for each tenant.  That might make sense in a low-volume scenario.  However, consider what happens when you have potentially 1000 tenants (ex. a freemium business model).

Ideally, I could have a single code base deployed to a single Azure Web account.  My AspNetMVC5 app would just handle the domain mapping ... for a given requested domain, look up the tenant ID (or use a Partition Key convention).  For the given request El Camino would look in a single set of tables for the particular tenant (PK) + user (RK) combination.

**Comment by DeveloperUniversity** [comment]
BTW, I would be willing to help implement this.  However it would be a breaking change for those already using El Camino.

**Comment by dlmelendez** [comment]
@DeveloperUniversity I see where you want to take your code and yes this would be a big change to the existing code base. Here is my thought on key generation after thinking through this kind of request and other requests that feel strongly how keys should be managed... In the next release, I am planning to open up the basekeyhelper class to be extended and added as a generic parameter to the context constructor. With this change, people can keep this existing urikeyhelper (and I can finally move to a hashkeyhelper already checked in but never fully implemented) or they could extend and override the key handling at their own risk. Would this type work for what you are trying to accomplish? thoughts?
Thanks, 
Dave

**Comment by DeveloperUniversity** [comment]
First of all, I love what you've done.  I strongly commend you and encourage you to continue.

Second, thanks for the super fast response.

Third, the basekeyhelper class idea could help.  At least, it would get me past that hurdle, I think.

I'm in research mode right now trying to understand how ASP.NET Identity works (esp. in light of a multi-tenant scenario).
