### ISSUE TITLE
Multitenancy support

### ISSUE THREAD

**Issue by espray** [dlmelendez/identityazuretable#32]
Is multi tenant supported by either

- StorageConnectionString per tenant
- Individual tables per tenant
- Tenant id on the ApplicationUser

If so, any samples.

**Comment by dlmelendez** [comment]
The easiest way to implement a multi-tenant environment would to leverage the table naming prefix for each tenant. https://dlmelendez.github.io/identityazuretable/#/walkthroughcore2 take a look at the IdentityConfiguration.TablePrefix property to add a prefix to the tables within the same storage account. Hopefully, this approach works for you.
