### ISSUE TITLE
Password Rules

### ISSUE THREAD

**Issue by aduwillie** [dlmelendez/identityazuretable#4]
I've hooked up your library to my project. To be honest, it's a great piece of work. But, how do i set password rules like in the EF library?

**Comment by dlmelendez** [comment]
Password rules are handled as part of the MS Identity Framework via the UserManager.PasswordValidator. See [https://github.com/dlmelendez/identityazuretable/blob/master/sample/samplemvc/App_Start/IdentityConfig.cs](url) line 38: `            // Configure validation logic for passwords
            manager.PasswordValidator = new PasswordValidator
            {
                RequiredLength = 6,
                RequireNonLetterOrDigit = true,
                RequireDigit = true,
                RequireLowercase = true,
                RequireUppercase = true,
            };
`
**Or** if you are using the identity core:
[https://github.com/dlmelendez/identityazuretable/blob/v1.0/sample/samplemvccore/Startup.cs](url)
Line 45 add:
`            services.AddIdentity<ApplicationUser, IdentityRole>( (options)=>
            {
                options.Password.RequireDigit = true;
                options.Password.RequireNonAlphanumeric = false; //etc.
            })
`

**Comment by aduwillie** [comment]
Thanks pal. I'd say, keep up the good work
