### ISSUE TITLE
ProjectUrl on NuGet is out of date

### ISSUE THREAD

**Issue by MatthewSteeples** [dlmelendez/identityazuretable#41]
Very minor issue, but the Project URL when you find this package on NuGet is still showing https://identityazuretable.codeplex.com

**Comment by dlmelendez** [comment]
@MatthewSteeples I will get this fixed in the next release. Thank you!

**Comment by dlmelendez** [comment]
The project url looks correct on nuget.org and in the vs nuget package manager.
