### ISSUE TITLE
Improper string escaping (possible security issue)

### ISSUE THREAD

**Issue by davidnx** [dlmelendez/identityazuretable#42]
Class [`UriEncodeKeyHelper`](https://github.com/dlmelendez/identityazuretable/blob/31244dd3167fdfeb049a0bbb4dcbce26debd1ce5/src/ElCamino.AspNetCore.Identity.AzureTable/Helpers/UriEncodeKeyHelper.cs) does not properly escape user input and different strings can be escaped into the same value, potentially opening up space for security issues.

E.g. method [`UriEncodeKeyHelper.EscapeKey`](https://github.com/dlmelendez/identityazuretable/blob/31244dd3167fdfeb049a0bbb4dcbce26debd1ce5/src/ElCamino.AspNetCore.Identity.AzureTable/Helpers/UriEncodeKeyHelper.cs#L81) would produce the same outputs for inputs `a+b@example.com` and `a_2bb@example.com`.

Additionally, the use of `_` as both the delimiter and the replacement for `%` encoding leads to additional ambiguity.

Suggested fix:

1. In `Constants.cs`, use `|` instead of `_` as the field delimiter

2. In `UriEncodeKeyHelper.cs`, replace occurrences of `"{0}_{1}"` with `"{0}|{1}"`

3. In `UriEncodeKeyHelper.EscapeKey`, replace the escaping code with something like:
   ```cs
   return System.Uri.EscapeDataString(keyUnsafe)
     // Percent-encode underscore even though it is an 'unreserved character' (see https://www.ietf.org/rfc/rfc2396.txt) because we use it instead of "%" in our encoding.
     .Replace("_", "%5F")
     .Replace("%", "_").ToUpper();
   ```

Note: I am not submitting a PR because I haven't had time to fully test the suggestions above. Additionally, some effort is needed to make these changes without breaking existing clients.

**Comment by dlmelendez** [comment]
@davidnx I get what you are saying. I believe the solution here is to finishing merging the pr for #35 . That way, the immutable identifier is exposed in the claims and these ids formatted for ATS keys stay internal to the library/app domain.

**Comment by dlmelendez** [comment]
v2.2.1 fixed.
