### ISSUE TITLE
Breaking Changes in 2.2?

### ISSUE THREAD

**Issue by tbasallo** [dlmelendez/identityazuretable#49]
I upgraded to 2.2 not thinking to much about it and it seems that there are breaking changes related to how usernames are saved based on user ID and user names (from what I was able to walk though in the latest commits). Logins that previously worked no longer work.

Recreating the same user created different entries.

Is that right?

**Comment by dlmelendez** [comment]
Yes, please check the release notes for breaking changes https://github.com/dlmelendez/identityazuretable/releases . The instructions for upgrading can be found here https://dlmelendez.github.io/identityazuretable/#/migration

**Comment by tbasallo** [comment]
Thanks, worked as advertised.
