### ISSUE TITLE
Store does not implement IQueryableUserStore<TUser>

### ISSUE THREAD

**Issue by critot** [dlmelendez/identityazuretable#5]
Hi, 
when I try to get all users stored in aspnetusers table:
var users = _userManager.Users;

I get this error

NotSupportedException: Store does not implement IQueryableUserStore<TUser>.
get_Users

thank you

**Comment by dlmelendez** [comment]
This is due to the azure storage library not supporting linq queries. Any help on implementing the expression filter would be appreciated and kind of tricky to make it perform well.

**Comment by mstrong64** [comment]
There is an implementation of IQueryable at https://github.com/dtretyakov/WindowsAzure. Personally I would be inclined to get a list of users another way :)

**Comment by am11** [comment]
I implemented a single sign-on service using this David's ElCamino table storage provider. One of the requirement was to get all Users loaded in memory at the application startup (singleton service).

Although bit of a performance hit, but I managed to simulate the "IQueryably get-all-users" behavior using this patch (on top of some old commit.. from Codeplex days):

```diff
-        IUserLoginStore<TUser> 
-        , IUserClaimStore<TUser> 
+        IUserLoginStore<TUser>, 
+        IQueryableUserStore<TUser>, IUserClaimStore<TUser> 
         , IUserRoleStore<TUser> 
         , IUserPasswordStore<TUser> 
         , IUserSecurityStampStore<TUser> 
@@ -223,6 +223,9 @@ await Task.WhenAll(_userTable.ExecuteAsync(TableOperation.Insert(item), cancella
             try 
             { 
                 await Task.WhenAll(tasks.ToArray()); 
+                var listified = _allUsers.ToList(); 
+                listified.Add(user); 
+                _allUsers = listified.AsQueryable(); 
                 return IdentityResult.Success; 
             } 

             catch (AggregateException aggex) 
@@ -832,7 +835,7 @@ public virtual Task<bool> IsInRoleAsync(TUser user, string roleName, Cancellatio
                 user.Roles.Remove(item);
                 TableOperation deleteOperation = TableOperation.Delete(item); 
-                await _userTable.ExecuteAsync(deleteOperation); 
+                await _userTable.ExecuteAsync(deleteOperation, cancellationToken); 
             } 
         } 
@@ -1126,6 +1129,10 @@ private TUser ChangeUserName(TUser user)
         public TContext Context { get; private set; } 
+        private IQueryable<TUser> _allUsers; 
+ 
+        public IQueryable<TUser> Users => _allUsers ??
+            (_allUsers = GetUsersAggregateAsync(new TableQuery()).Result.AsQueryable());
```

Each time a user is created, it updates the in-memory cache. The 'onion' architecture of ASP.NET Identity f/w eventually calls this `_store.Users` property, on each `_userManager.Users` call.

Note that it is an unwarranted territory as the framework internally re-instantiates the store object at different occasions, so it ends up calling `GetUsersAggregateAsync( .. )` everytime for certain operations (I think for each `GetClaimsAsync` or such; found it during the debug session).

**Comment by dlmelendez** [comment]
There may be some hope to bring this back with the Storage team looking to bring back linq in netstandard2.0 release: https://github.com/Azure/azure-storage-net/issues/491

**Comment by dlmelendez** [comment]
Putting this into v5 for basic query functionality.

**Comment by dlmelendez** [comment]
fixed in v5-rc2.
