### ISSUE TITLE
Not possible to override ReadEntity/WriteEntity

### ISSUE THREAD

**Issue by rvplauborg** [dlmelendez/identityazuretable#53]
Hello,

While using your library, thanks by the way, we had the need to store a more complex data type in our user table. Since Azure Table Storage does not support any complex data types, we had to hook into the `WriteEntity`/`ReadEntity` calls from `ITableEntity`. In `IdentityUser<T>`, which implements `ITableEntity`, the methods are not virtual, meaning we could not simply override them. Instead, we had to explicitly implement `ITableEntity` in our user model that extends `IdentityUser`.
Just wanted to let you know that this is a possible use case for your API, and it would be nice if those methods were virtual so that people can hook into them and call their serialization logic if needed :)

Best regards

**Comment by dlmelendez** [comment]
Easy enough. I will get this into a minor release.
