### ISSUE TITLE
Trying to use this in API project

### ISSUE THREAD

**Issue by ArvindRSingh** [dlmelendez/identityazuretable#57]
`services.AddIdentityServer()
                .AddApiAuthorization<CloudUser, CloudContext>();`

It shows 2 errors:

1. Error	CS0311	The type 'DataAccess.CloudContext' cannot be used as type parameter 'TContext' in the generic type or method 'IdentityServerBuilderConfigurationExtensions.AddApiAuthorization<TUser, TContext>(IIdentityServerBuilder)'. There is no implicit reference conversion from 'DataAccess.CloudContext' to 'Microsoft.EntityFrameworkCore.DbContext'.	Api	C:\Users\arvin\Documents\Source\Projects\...\Api\Startup.cs	67	Active
2. Error	CS0311	The type 'DataAccess.CloudContext' cannot be used as type parameter 'TContext' in the generic type or method 'IdentityServerBuilderConfigurationExtensions.AddApiAuthorization<TUser, TContext>(IIdentityServerBuilder)'. There is no implicit reference conversion from 'DataAccess.CloudContext' to 'IdentityServer4.EntityFramework.Interfaces.IPersistedGrantDbContext'.	Api	C:\Users\arvin\Documents\Source\Projects\...\Api\Startup.cs	67	Active

Further, could not modify dlmelendez/identityazuretable project to make ElCamino.AspNetCore.Identity.AzureTable.IdentityCloudContext derive from Microsoft.EntityFrameworkCore.DbContext, gives Microsoft.EntityFrameworkCore is missing.

**Comment by dlmelendez** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#configuration-through-code 
.AddApiAuthorization is an extension of IdentityServer to configure IdentityServer configuration store. This project does not affect the .AddApiAuthorization extension method for IdentityServer.
This project only manages the user, role, claims and token store for aspnet identity. To use this project with identity server you will need to setup the configuration (as described on the quickstart) e.g.
 // Add Elcamino Azure Table Identity services.
            services.AddIdentity<CloudUser, IdentityRole>((options) =>
            {
                options.User.RequireUniqueEmail = true;               
            })
                .AddAzureTableStores<IdentityCloudContext>(new Func<IdentityConfiguration>(() =>
                {
                    IdentityConfiguration idconfig = new IdentityConfiguration();
                    idconfig.TablePrefix = Configuration.GetSection("IdentityAzureTable:IdentityConfiguration:TablePrefix").Value;
                    idconfig.StorageConnectionString = Configuration.GetSection("IdentityAzureTable:IdentityConfiguration:StorageConnectionString").Value;
                    idconfig.LocationMode = Configuration.GetSection("IdentityAzureTable:IdentityConfiguration:LocationMode").Value;
                    return idconfig;
                }))
                .AddDefaultTokenProviders()
                .CreateAzureTablesIfNotExists<IdentityCloudContext>(); //can remove after first run;
// and
 // Adds IdentityServer
            services.AddIdentityServer(_ =>
            {
                
            })
           // <your IdentityServer config />
            **.AddAspNetIdentity<CloudUser>();**
//end
The process is very similiar to this identity server quickstart example: http://docs.identityserver.io/en/aspnetcore1/quickstarts/6_aspnet_identity.html 

Again, to use .AddApiAuthorization() extension, you with need to setup an identityserver configuration database and use that datacontext defined here: http://docs.identityserver.io/en/aspnetcore1/quickstarts/8_entity_framework.html

Hope this helps.

**Comment by dlmelendez** [comment]
Slight correction, .AddApiAuthorization is a Microsoft extension method, not an IdentityServer extension, but wraps several IdentityServer configuration properties.
