### ISSUE TITLE
UserManager.GetRolesAsync failing in 3.1 after migration from  1.7

### ISSUE THREAD

**Issue by savind** [dlmelendez/identityazuretable#58]
I  migrated from  1.7  to  latest using the tool. Used  samplemvccore to test.
login works fine, I  injected UserManager<IdentityUser> in home controller  and  used 
`var roles = UserManager.GetRolesAsync(user).Result;`
to test  roles. It always returns empty list.

Debugging it, I get  the  count of expected two  roles in  UserStore.cs  on line number 140.
`int userRoleTotalCount = userRoles.Count();`
But the query after that  returns empty list.

BTW Role table is empty for some reason.

**Comment by savind** [comment]
MIgrating roles also did not help. still  the Roles table is  empty.

**Comment by dlmelendez** [comment]
when you run 
ElCamino.Identity.AzureTable.DataUtility.exe /preview:roles
does it show any roles to migrate?

**Comment by savind** [comment]
> when you run
> ElCamino.Identity.AzureTable.DataUtility.exe /preview:roles
> does it show any roles to migrate?

ElCamino.Identity.AzureTable.DataUtility.exe /preview:roles result is 0.

**Comment by savind** [comment]
I updated the code in the UserMigration.cs to work around the issue. 
In function ConvertToTargetUserEntities, while copying roles (block starting at line number 200), I added following lines to update the roles table.

`string roletablepk = _keyHelper.GeneratePartitionKeyIdentityRole(roleName);
string roletablerk = _keyHelper.GenerateRowKeyIdentityRole(roleName);
DynamicTableEntity tgtDteRole = new DynamicTableEntity(roletablepk, roletablerk);
tgtDteRole.Properties["UserId"] = new EntityProperty(userId);
tgtDteRole.Properties["Name"] = new EntityProperty(roleName);
tgtDteRole.Properties["KeyVersion"] = new EntityProperty(_keyHelper.KeyVersion);
roleUserEntities.Add(tgtDteRole);`

This solved my issue. But I could not understand the purpose of the Roles table. Looking at the code in UserStore.GetRolesAsync, we already query the roles from Users table, why is it needed to query again from roles table? Am I missing something?

**Comment by dlmelendez** [comment]
This lookup logic is mirrored from  Microsoft.Identity library. I am glad you discovered a workaround.

**Comment by dlmelendez** [comment]
Need to investigate this further and target v6.0

**Comment by dlmelendez** [comment]
Unable to repro.
