### ISSUE TITLE
Adding User Role functionality to web app

### ISSUE THREAD

**Issue by elvogel** [dlmelendez/identityazuretable#59]
I'm using ASP.NET 3.1 Core and I'm trying to get user role functionality enabled and working so I can assign roles to users.

Following the 'instructions' and the source code to samplemvccore4, I get an app that has everything but user roles. When I try to follow ASP.NET documentation and add something like this in my startup:
```csharp
                .AddRoles<IdentityUserRole>()
```
It blows up the `CreateAzureTablesIfNotExists` method in `IdentityAzureTableBuilderExtensions`. 

So, how do you enable user roles in an ASP.NET application using this library?

**Comment by dlmelendez** [comment]
try this:
services.AddIdentity<IdentityUser, ElCamino.AspNetCore.Identity.AzureTable.Model.IdentityRole>(options =>
            // services.AddDefaultIdentity<IdentityUser>(options =>
            {
                options.SignIn.RequireConfirmedAccount = true;
                options.User.RequireUniqueEmail = true;
            })  
This is part of the MS Identity Framework. It really isn't possible to address and maintain all of the configurations in the sample. The MS team has de-emphasized the use of roles and favored the use of claims instead. The above code should get you going.

**Comment by dlmelendez** [comment]
will be merged to master next release

**Comment by elvogel** [comment]
Okay thanks for the response. Two more questions:
- When is the next release? 
- What is the recommendation for setting up and using claims? Will there be documentation?

Kudos for coming out with a huge money saving Identity library, it's really appreciated!

**Comment by dlmelendez** [comment]
@elvogel next release will be targeting after .NET 5 in November.
Claims documentation can be found here: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-3.1 
Most of the identity related implementation how to's are addressed in the MS Identity Core documentation.

**Comment by elvogel** [comment]
When I try using the code you mentioned above, it creates an additional entry in the Users table with the role name. When I try querying for it using the `_userManager.GetRolesAsync` method, it doesn't pull up. It also doesn't seem to work with the `[Authorize(Role = "RoleName"]` attribute.

**Comment by dlmelendez** [comment]
@elvogel  The test AddRemoveUserRole starting line 66 https://github.com/dlmelendez/identityazuretable/blob/966cbb5b961b644bbb7d8f86b94db26c2df1d795/tests/ElCamino.AspNetCore.Identity.AzureTable.Tests/BaseUserStoreTests.cs shows the path to creating a role and testing GetRolesAsync(). You will need to create the role first in with the RoleStore.Create and then add it to the user with the UserManager.AddToRoleAysnc(). Once this is setup correctly and the _userManager.GetRolesAsync returns the role for the user, the Authorize attribute should work as expected.

**Comment by dlmelendez** [comment]
closed in v5-rc2.
