### ISSUE TITLE
Changing Username does not purge index records

### ISSUE THREAD

**Issue by AlexMedia** [dlmelendez/identityazuretable#67]
I'm currently working on a project with the following set-up:

- ASP.NET Core MVC 3.1.8, using the default Identity platform
- Default configuration: username = email, requiring unique emails and confirmed accounts
- Using ElCamino.AspNetCore.Identity.AzureTable v3.1.0, acquired from NuGet

I have come across an issue whereby the old username is not freed up after changing it via the Account area.

Steps to reproduce:
1. Create an account via the normal registration and confirmation flow
2. Log on, go into Account > Email, change Email, go through confirmation flow
3. Confirm that you can log in with the new email address
4. Log off
5. Try to register a new account using the previously used email address. The following error message appears:
> User name 'old-email@address.tld' is already taken.

I've done some investigation, and I suspect that the issue is caused by records in the AspNetIndex table not being cleaned up properly when the rename takes place. 

[In the source](https://github.com/dlmelendez/identityazuretable/blob/f0442e191b07aad513712abeaa122492fee8278e/src/ElCamino.AspNetCore.Identity.AzureTable/UserOnlyStore.cs#L859) I see that `SetEmailAsync` is overridden to purge records from the index table, but no such thing seems to happen for `SetUserNameAsync`.

**Comment by dlmelendez** [comment]
@AlexMedia appreciate you filing this issue. Assigned to next release.

**Comment by dlmelendez** [comment]
fixed in v5-rc2
