### ISSUE TITLE
Register TContext class as Singleton, not Scoped

### ISSUE THREAD

**Issue by davidnx** [dlmelendez/identityazuretable#76]
`TContext` is currently registered in DI (code snippet below) as a scoped service, which means **a new one is created for each request**. This is sub-optimal for many reasons:

* Prevents re-use of Azure Table client instances across requests
* Requires a new TLS connection to Azure Table Storage each time
* If a server using this library is serving a lot of requests, it could quickly run out of SNAT ports due to establishing so many connections in short periods of time
* Unnecessary recomputations (e.g. storage connection string is re-parsed each time)

Suggestion is to change the line below to `AddSingleton`. Thoughts?
https://github.com/dlmelendez/identityazuretable/blob/62f63b216dc1b67c91e4fe45886d0bb32287e2c1/src/ElCamino.AspNetCore.Identity.AzureTable/IdentityAzureTableBuilderExtensions.cs#L32

Note: To do this, we'd also have to fix a few related lifecycle issues e.g. `UserOnlyStore.Dispose(bool)` shouldn't try to dispose `this.Context` -- it is not the owner of the context. The DI container can handle that instead.

https://github.com/dlmelendez/identityazuretable/blob/62f63b216dc1b67c91e4fe45886d0bb32287e2c1/src/ElCamino.AspNetCore.Identity.AzureTable/UserOnlyStore.cs#L233-L236

**Comment by dlmelendez** [comment]
Seems legit, this was a carryover from previous sdk iterations where the tableClient was not thread safe. This looks safe to do, but need to investigate if the next Azure.Data.Tables sdk will have a tableClient that is also thread safe.
