### ISSUE TITLE
UserManager.CreateAsync is not adding user to the database

### ISSUE THREAD

**Issue by SVarasteh** [dlmelendez/identityazuretable#77]
Hello,

We are using this library and sometimes we noticed that user is not adding to the database
after UserManager.CreateAsync.
We have logs for result of this function and everything looks successful in the logs but actually the user is missing in the database and this issue happens intermittently.

Any help or guideline will be appreciated how to fix this issue.
Thanks
Saeideh

**Comment by dlmelendez** [comment]
Closing for lack of information to repro and activity.
