### ISSUE TITLE
IdentityCloudContext being disposed after first call to controller

### ISSUE THREAD

**Issue by mcbridd** [dlmelendez/identityazuretable#85]
Firstly, thank you for the work put into this library.

I'm experiencing a strange issue when using the library with .NET Core 5, where I'm trying to use a UserManager with a custom IdentityUser object in my project. When I use DI with the controller, my first call to the controller works (i.e. to display the page). A post back to the same controller results in the following error:

ObjectDisposedException: Cannot access a disposed object.
Object name: 'ApplicationDbContext'.
ElCamino.AspNetCore.Identity.AzureTable.IdentityCloudContext.ThrowIfDisposed() in IdentityCloudContext.cs, line 90

I've noticed that the IdentityCloudContext is being created prior to the constructor being called in the controller but immediately after the controller returns the view, the Dispose code for the IdentityCloudContext is being called. This means that any subsequent call to the same controller is resulting in the above error.

This is the constructor for my controller:

        public AccountController(UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ILogger<AccountController> logger,
            CaptchaVerificationService verificationService,
            IOptions<OrganisationSettings> organisationSettings) : base()
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _verificationService = verificationService;
            _organisationSettings = organisationSettings.Value;
        }

This is the code for my first method on the controller:

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Login()
        {
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
            var model = new SecurityViewModel(SecurityPageEnum.LoginPage);
            model.CaptchaClientKey = _verificationService.ClientKey;
            return View(model);
        }

Immediately after this call, the following occurs:

ElCamino.AspNetCore.Identity.AzureTable.IdentityCloudContext.Dispose(bool disposing) Line 101 in /Users/darrenmcbride/Documents/Projects/Dunluvly/Application/ElCamino.AspNetCore.Identity.AzureTable/IdentityCloudContext.cs:101
ElCamino.AspNetCore.Identity.AzureTable.IdentityCloudContext.Dispose() Line 95 in /Users/darrenmcbride/Documents/Projects/Dunluvly/Application/ElCamino.AspNetCore.Identity.AzureTable/IdentityCloudContext.cs:95
ElCamino.AspNetCore.Identity.AzureTable.UserOnlyStore<Dunluvly.Data.Entities.ApplicationUser, Dunluvly.Data.ApplicationDbContext, string, ElCamino.AspNetCore.Identity.AzureTable.Model.IdentityUserClaim, ElCamino.AspNetCore.Identity.AzureTable.Model.IdentityUserLogin, ElCamino.AspNetCore.Identity.AzureTable.Model.IdentityUserToken>.Dispose(bool disposing) Line 239 in /Users/darrenmcbride/Documents/Projects/Dunluvly/Application/ElCamino.AspNetCore.Identity.AzureTable/UserOnlyStore.cs:239
ElCamino.AspNetCore.Identity.AzureTable.UserStore<Dunluvly.Data.Entities.ApplicationUser, ElCamino.AspNetCore.Identity.AzureTable.Model.IdentityRole, string, ElCamino.AspNetCore.Identity.AzureTable.Model.IdentityUserLogin, ElCamino.AspNetCore.Identity.AzureTable.Model.IdentityUserRole, ElCamino.AspNetCore.Identity.AzureTable.Model.IdentityUserClaim, ElCamino.AspNetCore.Identity.AzureTable.Model.IdentityUserToken, Dunluvly.Data.ApplicationDbContext>.Dispose(bool disposing) Line 513 in /Users/darrenmcbride/Documents/Projects/Dunluvly/Application/ElCamino.AspNetCore.Identity.AzureTable/UserStore.cs:513
ElCamino.AspNetCore.Identity.AzureTable.UserOnlyStore<Dunluvly.Data.Entities.ApplicationUser, Dunluvly.Data.ApplicationDbContext, string, ElCamino.AspNetCore.Identity.AzureTable.Model.IdentityUserClaim, ElCamino.AspNetCore.Identity.AzureTable.Model.IdentityUserLogin, ElCamino.AspNetCore.Identity.AzureTable.Model.IdentityUserToken>.Dispose() Line 230 in /Users/darrenmcbride/Documents/Projects/Dunluvly/Application/ElCamino.AspNetCore.Identity.AzureTable/UserOnlyStore.cs:230

This is my startup code:

        public void ConfigureServices(IServiceCollection services)
        {
            var connectionString = Configuration["BlobStore:ConnectionString"];

            var identity = services.AddDefaultIdentity<ApplicationUser>(options =>
            {
                options.SignIn.RequireConfirmedAccount = true;
                options.User.RequireUniqueEmail = true;
                options.Password.RequireDigit = true;
                options.Password.RequiredLength = 6;
                options.Password.RequireLowercase = true;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = true;

                options.Lockout = new LockoutOptions()
                {
                    DefaultLockoutTimeSpan = TimeSpan.FromHours(1),
                    MaxFailedAccessAttempts = 5,
                    AllowedForNewUsers = true
                };
            })
            .AddRoles<IdentityRole>()
            .AddAzureTableStores<ApplicationDbContext>(new Func<IdentityConfiguration>(() =>
            {
                IdentityConfiguration config = new()
                {
                    StorageConnectionString = connectionString,
                    IndexTableName = "AspNetIndex",
                    RoleTableName = "AspNetRoles",
                    UserTableName = "AspNetUsers",
                };
                return config;
            }))
            .CreateAzureTablesIfNotExists<ApplicationDbContext>()
            .AddDefaultTokenProviders();

            services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.HttpOnly = true;
                options.ExpireTimeSpan = TimeSpan.FromDays(1);
                options.LoginPath = $"/Account/Login";
                options.LogoutPath = $"/Account/Logout";
                options.AccessDeniedPath = $"/Account/AccessDenied";
                options.SlidingExpiration = false;
            });

            services.Configure<SecurityStampValidatorOptions>(options =>
            {
                options.ValidationInterval = TimeSpan.FromSeconds(1);
            });

            services.AddScoped<IUserRepository, UserRepository>();
            services.AddScoped<CaptchaVerificationService>();

            services.AddSingleton(new TableServiceClient(connectionString));
            services.AddSingleton<ITableStoreService<Subscriber>, TableStoreService<Subscriber>>();

            services.AddHttpContextAccessor();

            services.AddOptions<CaptchaSettings>()
                .Bind(Configuration.GetSection("Captcha"));
            services.AddOptions<BlobStoreSettings>()
                .Bind(Configuration.GetSection("BlobStore"));

            services.AddSession(options =>
            {
                options.IdleTimeout = TimeSpan.FromMinutes(60);
                options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
                options.Cookie.SameSite = SameSiteMode.Strict;
                options.Cookie.HttpOnly = true;
                options.Cookie.IsEssential = true;
            });

            services.AddMvc();

            services.AddWebOptimizer(minifyJavaScript: false);
        }

Some search results are suggesting issues with 'async void', but I'm not using this anywhere.

Any ideas?

Thanks in advance,
Darren

**Comment by mcbridd** [comment]
I notice in issue 76 that the context is now declared as a singleton, but I've read in different places that UserManager is declared as scoped, so is this a possibility with my use of controllers? I'm not a DI expert, so I'm grasping at a few straws...

https://github.com/dlmelendez/identityazuretable/issues/76
https://github.com/aspnet/Identity/issues/1919
https://stackoverflow.com/questions/39369054/usermanager-dbcontext-already-disposed-in-middleware

**Comment by mcbridd** [comment]
To add further confusion, I noticed that these changes **are** in my code:
https://github.com/dlmelendez/identityazuretable/commit/a2460d28da5e27f2cd68fc7b18c432669742f6dc

But these changes **are not**:
https://github.com/dlmelendez/identityazuretable/commit/b1e15c46f9ba64c8fa05c362798c1d33d9b0dc77

**Comment by mcbridd** [comment]
Final update (I promise). By implementing the code in this change (which is missing when I downloaded the entire project as a ZIP file), I can confirm that my project is now working:
https://github.com/dlmelendez/identityazuretable/commit/b1e15c46f9ba64c8fa05c362798c1d33d9b0dc77

I will leave this ticket open for the authors to decide whether my approach is correct, and whether there's an issue with the current code base.

Thanks,
Darren

**Comment by dlmelendez** [comment]
@mcbridd  Interesting. Out of curiosity, does the issue exist with the nuget package or just when you download the code from zip file?
