### ISSUE TITLE
Trouble with adding to Blazor 5.0 Project

### ISSUE THREAD

**Issue by Terrence77** [dlmelendez/identityazuretable#86]
I love your great libs for using TS for Identity.  I can't seem to get it working on a Blazor project.  Been working for 2 nights on a dozen different issues but can't seem to nail it.  

Have you tried your code on a Blazor project?

Thanks for any help you might give.

**Comment by Terrence77** [comment]
Oh, something I can overcome with search and replace, but it seems that your "dotnet new rzp-id-azure-tables" templates replace most of the NameSpace names with lowercase namespace.

So using and namespaces like BlazorApp1.Data becomes blazorapp1.Data after running the command.

**Comment by dlmelendez** [comment]
Need to investigate template naming: https://github.com/dotnet/templating/wiki/Naming-and-default-value-forms

**Comment by dlmelendez** [comment]
Fixed in latest release tested with net8.0 blazor project
